services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 60
      container_to_watch: django-app
      WATCHTOWER_NO_PULL: true


  django-app:
    image: lucasnicolas/django-app
    ports:
      - "8000:8000"
    container_name: django-app