on:
  push:
    branches:
      - main

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker
        run: echo ${{secrets.DOCKER_HUB_PASSWORD}} | docker login --username ${{vars.DOCKER_HUB_USERNAME}} --password-stdin
#
      - name: Build Dockerfile
        run: docker build . -t ${{vars.DOCKER_HUB_USERNAME}}/hola
#
      - name: Push to Dockerhub
        run: docker push ${{vars.DOCKER_HUB_USERNAME}}/hola