on:
  push:
    branches:
      - main

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: docker build . -t lucasnicolas/hola